### ISSUE TITLE
tracking CPU usage, using Embassy

### ISSUE THREAD

**Issue by lure23** [lure23/Zoo-ESP32_Cx#9]
Check, whether there's prior art on how to know, how close to "the edge" an ESP32 family MCU is performing, running things with Embassy.

Embassy allows multitasking. 

- [ ] Does it, on its own, have a mechanism for e.g. recording how long the executor has been asleep (exactly what we'd want to know)?
- [ ] Have others brought this up?
- [ ] If no current solution, make a task that simply logs how frequently it gets called (if it's the only executable task, it would get called in almost busy loop fashion). Perhaps we can estimate the headroom.

---

- https://www.giacomocaironi.dev/posts/measuring-cpu-usage-with-rust-embassy/ (blog, Jun 2024)
- https://github.com/embassy-rs/embassy/pull/2759 (PR, April '24)
- ["A CPU usage monitor for the RTFM framework"](https://blog.japaric.io/cpu-monitor/) (blog, Jun '17)

Created ["FR: Method for measuring CPU load"](https://github.com/embassy-rs/embassy/issues/3465)

**Comment by lure23** [comment]
Just timing (and logging) the event loop is enough.
